package msiresult

import "github.com/leafbridge/leafbridge-deploy/lbdeploy"

// InfoMap holds descriptive information for exit codes produced by msiexec.
//
// https://learn.microsoft.com/en-us/windows/win32/msi/error-codes
var InfoMap = map[ExitCode]lbdeploy.ExitCodeInfo{
	Success:                       {Name: "ERROR_SUCCESS", Description: "The action completed successfully.", OK: true},
	InvalidData:                   {Name: "ERROR_INVALID_DATA", Description: "The data is invalid."},
	InvalidParameter:              {Name: "ERROR_INVALID_PARAMETER", Description: "One of the parameters was invalid."},
	CallNotImplemented:            {Name: "ERROR_CALL_NOT_IMPLEMENTED", Description: "This value is returned when a custom action attempts to call a function that can't be called from custom actions. The function returns the value ERROR_CALL_NOT_IMPLEMENTED."},
	ApphelpBlock:                  {Name: "ERROR_APPHELP_BLOCK", Description: "If Windows Installer determines a product might be incompatible with the current operating system, it displays a dialog box informing the user and asking whether to try to install anyway. This error code is returned if the user chooses not to try the installation."},
	InstallServiceFailure:         {Name: "ERROR_INSTALL_SERVICE_FAILURE", Description: "The Windows Installer service couldn't be accessed. Contact your support personnel to verify that the Windows Installer service is properly registered."},
	InstallUserexit:               {Name: "ERROR_INSTALL_USEREXIT", Description: "The user canceled installation."},
	InstallFailure:                {Name: "ERROR_INSTALL_FAILURE", Description: "A fatal error occurred during installation."},
	InstallSuspend:                {Name: "ERROR_INSTALL_SUSPEND", Description: "Installation suspended, incomplete."},
	UnknownProduct:                {Name: "ERROR_UNKNOWN_PRODUCT", Description: "This action is only valid for products that are currently installed."},
	UnknownFeature:                {Name: "ERROR_UNKNOWN_FEATURE", Description: "The feature identifier isn't registered."},
	UnknownComponent:              {Name: "ERROR_UNKNOWN_COMPONENT", Description: "The component identifier isn't registered."},
	UnknownProperty:               {Name: "ERROR_UNKNOWN_PROPERTY", Description: "This is an unknown property."},
	InvalidHandleState:            {Name: "ERROR_INVALID_HANDLE_STATE", Description: "The handle is in an invalid state."},
	BadConfiguration:              {Name: "ERROR_BAD_CONFIGURATION", Description: "The configuration data for this product is corrupt. Contact your support personnel."},
	IndexAbsent:                   {Name: "ERROR_INDEX_ABSENT", Description: "The component qualifier not present."},
	InstallSourceAbsent:           {Name: "ERROR_INSTALL_SOURCE_ABSENT", Description: "The installation source for this product isn't available. Verify that the source exists and that you can access it."},
	InstallPackageVersion:         {Name: "ERROR_INSTALL_PACKAGE_VERSION", Description: "This installation package can't be installed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service."},
	ProductUninstalled:            {Name: "ERROR_PRODUCT_UNINSTALLED", Description: "The product is uninstalled."},
	BadQuerySyntax:                {Name: "ERROR_BAD_QUERY_SYNTAX", Description: "The SQL query syntax is invalid or unsupported."},
	InvalidField:                  {Name: "ERROR_INVALID_FIELD", Description: "The record field does not exist."},
	InstallAlreadyRunning:         {Name: "ERROR_INSTALL_ALREADY_RUNNING", Description: "Another installation is already in progress. Complete that installation before proceeding with this install. For information about the mutex, see _MSIExecute Mutex."},
	InstallPackageOpenFailed:      {Name: "ERROR_INSTALL_PACKAGE_OPEN_FAILED", Description: "This installation package couldn't be opened. Verify that the package exists and is accessible, or contact the application vendor to verify that this is a valid Windows Installer package."},
	InstallPackageInvalid:         {Name: "ERROR_INSTALL_PACKAGE_INVALID", Description: "This installation package couldn't be opened. Contact the application vendor to verify that this is a valid Windows Installer package."},
	InstallUiFailure:              {Name: "ERROR_INSTALL_UI_FAILURE", Description: "There was an error starting the Windows Installer service user interface. Contact your support personnel."},
	InstallLogFailure:             {Name: "ERROR_INSTALL_LOG_FAILURE", Description: "There was an error opening installation log file. Verify that the specified log file location exists and is writable."},
	InstallLanguageUnsupported:    {Name: "ERROR_INSTALL_LANGUAGE_UNSUPPORTED", Description: "This language of this installation package isn't supported by your system."},
	InstallTransformFailure:       {Name: "ERROR_INSTALL_TRANSFORM_FAILURE", Description: "There was an error applying transforms. Verify that the specified transform paths are valid."},
	InstallPackageRejected:        {Name: "ERROR_INSTALL_PACKAGE_REJECTED", Description: "This installation is forbidden by system policy. Contact your system administrator."},
	FunctionNotCalled:             {Name: "ERROR_FUNCTION_NOT_CALLED", Description: "The function couldn't be executed."},
	FunctionFailed:                {Name: "ERROR_FUNCTION_FAILED", Description: "The function failed during execution."},
	InvalidTable:                  {Name: "ERROR_INVALID_TABLE", Description: "An invalid or unknown table was specified."},
	DatatypeMismatch:              {Name: "ERROR_DATATYPE_MISMATCH", Description: "The data supplied is the wrong type."},
	UnsupportedType:               {Name: "ERROR_UNSUPPORTED_TYPE", Description: "Data of this type isn't supported."},
	CreateFailed:                  {Name: "ERROR_CREATE_FAILED", Description: "The Windows Installer service failed to start. Contact your support personnel."},
	InstallTempUnwritable:         {Name: "ERROR_INSTALL_TEMP_UNWRITABLE", Description: "The Temp folder is either full or inaccessible. Verify that the Temp folder exists and that you can write to it."},
	InstallPlatformUnsupported:    {Name: "ERROR_INSTALL_PLATFORM_UNSUPPORTED", Description: "This installation package isn't supported on this platform. Contact your application vendor."},
	InstallNotused:                {Name: "ERROR_INSTALL_NOTUSED", Description: "Component isn't used on this machine."},
	PatchPackageOpenFailed:        {Name: "ERROR_PATCH_PACKAGE_OPEN_FAILED", Description: "This patch package couldn't be opened. Verify that the patch package exists and is accessible, or contact the application vendor to verify that this is a valid Windows Installer patch package."},
	PatchPackageInvalid:           {Name: "ERROR_PATCH_PACKAGE_INVALID", Description: "This patch package couldn't be opened. Contact the application vendor to verify that this is a valid Windows Installer patch package."},
	PatchPackageUnsupported:       {Name: "ERROR_PATCH_PACKAGE_UNSUPPORTED", Description: "This patch package can't be processed by the Windows Installer service. You must install a Windows service pack that contains a newer version of the Windows Installer service."},
	ProductVersion:                {Name: "ERROR_PRODUCT_VERSION", Description: "Another version of this product is already installed. Installation of this version can't continue. To configure or remove the existing version of this product, use Add/Remove Programs in Control Panel."},
	InvalidCommandLine:            {Name: "ERROR_INVALID_COMMAND_LINE", Description: "Invalid command line argument. Consult the Windows Installer SDK for detailed command-line help."},
	InstallRemoteDisallowed:       {Name: "ERROR_INSTALL_REMOTE_DISALLOWED", Description: "The current user isn't permitted to perform installations from a client session of a server running the Terminal Server role service."},
	SuccessRebootInitiated:        {Name: "ERROR_SUCCESS_REBOOT_INITIATED", Description: "The installer has initiated a restart. This message indicates success.", OK: true},
	PatchTargetNotFound:           {Name: "ERROR_PATCH_TARGET_NOT_FOUND", Description: "The installer can't install the upgrade patch because the program being upgraded may be missing or the upgrade patch updates a different version of the program. Verify that the program to be upgraded exists on your computer and that you have the correct upgrade patch."},
	PatchPackageRejected:          {Name: "ERROR_PATCH_PACKAGE_REJECTED", Description: "The patch package isn't permitted by system policy."},
	InstallTransformRejected:      {Name: "ERROR_INSTALL_TRANSFORM_REJECTED", Description: "One or more customizations aren't permitted by system policy."},
	InstallRemoteProhibited:       {Name: "ERROR_INSTALL_REMOTE_PROHIBITED", Description: "Windows Installer doesn't permit installation from a Remote Desktop Connection."},
	PatchRemovalUnsupported:       {Name: "ERROR_PATCH_REMOVAL_UNSUPPORTED", Description: "The patch package isn't a removable patch package."},
	UnknownPatch:                  {Name: "ERROR_UNKNOWN_PATCH", Description: "The patch isn't applied to this product."},
	PatchNoSequence:               {Name: "ERROR_PATCH_NO_SEQUENCE", Description: "No valid sequence could be found for the set of patches."},
	PatchRemovalDisallowed:        {Name: "ERROR_PATCH_REMOVAL_DISALLOWED", Description: "Patch removal was disallowed by policy."},
	InvalidPatchXml:               {Name: "ERROR_INVALID_PATCH_XML", Description: "The XML patch data is invalid."},
	PatchManagedAdvertisedProduct: {Name: "ERROR_PATCH_MANAGED_ADVERTISED_PRODUCT", Description: "Administrative user failed to apply patch for a per-user managed or a per-machine application that'is in advertised state."},
	InstallServiceSafeboot:        {Name: "ERROR_INSTALL_SERVICE_SAFEBOOT", Description: "Windows Installer isn't accessible when the computer is in Safe Mode. Exit Safe Mode and try again or try using system restore to return your computer to a previous state. Available beginning with Windows Installer version 4.0."},
	RollbackDisabled:              {Name: "ERROR_ROLLBACK_DISABLED", Description: "Couldn't perform a multiple-package transaction because rollback has been disabled. Multiple-package installations can't run if rollback is disabled. Available beginning with Windows Installer version 4.5."},
	InstallRejected:               {Name: "ERROR_INSTALL_REJECTED", Description: "The app that you're trying to run isn't supported on this version of Windows. A Windows Installer package, patch, or transform that has not been signed by Microsoft can't be installed on an ARM computer."},
	SuccessRebootRequired:         {Name: "ERROR_SUCCESS_REBOOT_REQUIRED", Description: "A restart is required to complete the install. This message indicates success. This does not include installs where the ForceReboot action is run.", OK: true},
}
